### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by LukeWheeldon** [salgozino/KlerosJurorDashboard#36]
This otherwise great website is not looking very legit using bare HTTP.

**Comment by salgozino** [comment]
It's true. I will add the certificate.
Thank you for reporting this.

**Comment by lanlan3322** [comment]
you can use Let's Encrypt. It is free and easy to setup.

**Comment by salgozino** [comment]
Thank you for your insights @lanlan3322 and for the request @LukeWheeldon 

Now HTTPS it's enabled in the site
