### ISSUE TITLE
Retention Data Seems Wrong

### ISSUE THREAD

**Issue by ferittuncer** [salgozino/KlerosJurorDashboard#49]
![Screenshot from 2021-07-06 18-37-54](https://user-images.githubusercontent.com/3106907/124628647-5ac9ea00-de89-11eb-89c7-9c73aaf86f0d.png)

**Comment by salgozino** [comment]
Indeed, with the changes to subgraph in the backend, retention data it's wrong. I will be fixing this asap

**Comment by salgozino** [comment]
Fixed in 5612ec8245ee90fd2183276d3edf1ccab2c81e18
