### ISSUE TITLE
Sort donors in descending order instead

### ISSUE THREAD

**Issue by greenlucid** [salgozino/KlerosJurorDashboard#70]
It's kinda funny but they're currently ordered in asc order by default?
I may PR this myself, let me check if I know how to do it
![image](https://user-images.githubusercontent.com/40367733/149830304-faf54928-abe3-4eb6-85f5-a209a07295b8.png)

**Comment by salgozino** [comment]
You are right!.

Let me test it and merge it, but seems ok the change.
